# Generated by Django 5.0.1 on 2024-02-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('integrantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('identidadSecreta', models.CharField(max_length=50)),
                ('emailContacto', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proeza', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('salvoMundo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Villano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('identidadSecreta', models.CharField(max_length=50)),
                ('emailContacto', models.EmailField(max_length=254)),
                ('poderes', models.CharField(max_length=50)),
            ],
        ),
    ]
